[theme]
primaryColor = "#8A80CC"  # Cor principal para botões e links
secondaryBackgroundColor = "#8A80CC"  # Cor de fundo da barra lateral
textColor = "#FFFFFF"  # Cor do texto principal
font = "sans serif"  # Fonte do texto
